### ISSUE TITLE
[Account settings] Email with instructions for changing password doesn't send after click on 'Change password' button

### ISSUE THREAD

**Issue by MariiaDakh** [ita-social-projects/horondi_client_be#1056]

**Comment by SirAndrii** [comment]
Check what emails are missing (change password, recover password, registration, buy, confirm email):

- [ ] localy
- [ ] from staging

**Comment by SirAndrii** [comment]
We have missed a sender method on the Backend, but I can't get any emails from Horondi.

**Comment by SirAndrii** [comment]
After an update, Google Api keys credentials settings were not refreshed. 
Fixed it. Now mails are working as it was before.

**Comment by MariiaDakh** [comment]
An email with  instructions for changing password still doesn't get

**Comment by SirAndrii** [comment]
> An email with instructions for changing password still doesn't get

![image](https://user-images.githubusercontent.com/24919819/153298233-1ab6e988-a1c8-414b-85fc-6db6f0566a87.png)
